SWE574/core/urls.py
from django.urls import path
from . import views
from .src.controllers import annotation_controller
from .src.utils import generate_preview

app_name = "core"

urlpatterns = [
    path("", views.feed, name="feed"),
    path("feed", views.feed, name="preview"),
    path("signup", views.signup, name="signup"),
    path("signin", views.signin, name="signin"),
    path("logout", views.logout, name="logout"),
    path("settings", views.settings, name="settings"),
    path("profile/<str:profile_owner_username>/", views.profile, name="profile"),
    path("about/", views.about, name="about"),
    path("delete_account", views.delete_account, name="delete_account"),
    path("delete_post", views.delete_post, name="delete_post"),
    path("preview/", generate_preview.generate_preview, name="generate"),
    path("search", views.search, name="search"),
    path("follow", views.follow, name="follow"),
    path("join", views.join, name="join"),
    path("tags", views.tags_index, name="tags_index"),
    path("tags/wiki-data-search", views.tag_wiki_data_search, name="tag_wiki_data_search"),
    path("tags/search", views.tags_search, name="tags_search"),
    path("tags/all", views.all_tags, name="all_tags"),
    path("tags/<str:tag_name>", views.tag_posts, name="tag_posts"),
    path("spaces", views.spaces_index, name="spaces_index"),
    path("spaces/search", views.spaces_search, name="spaces_search"),
    path("spaces/create", views.create_space, name="create_space"),
    path("spaces/all", views.all_spaces, name="all_spaces"),
    path("spaces/<str:space_name>", views.space_posts, name="space_posts"),
    path("post/detail/<str:post_id>", views.post_detail, name="post_detail"),
    path("post/create", views.create_post, name="create_post"),
    path("post/update", views.update_post, name="update_post"),
    path("post/like/<str:post_id>", views.like_post, name="like_post"),
    path("post/dislike/<str:post_id>", views.dislike_post, name="like_post"),
    path("post/bookmark_post", views.bookmark_post, name="bookmark_post"),
    path("fetch-og-tags", views.fetch_og_tags, name="fetch_og_tags"),
    path("annotations/create", annotation_controller.create_annotation, name="create_annotation"),
    path("annotations/search", annotation_controller.get_annotations, name="get_annotations"),
    path("badges", views.badges, name="badges"),
    path('add-comment/<uuid:post_id>/', views.add_comment, name='add_comment'),
    path('delete-comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path("following_list", views.following_list, name="following_list"),
    path("follower_list", views.follower_list, name="follower_list"),
]

core/urls.py
from django.urls import path
from . import views
from .src.utils import generate_preview

app_name = "core"

urlpatterns = [
    path("", views.feed, name="feed"),
    path("feed", views.feed, name="preview"),
    path("signup", views.signup, name="signup"),
    path("signin", views.signin, name="signin"),
    path("logout", views.logout, name="logout"),
    path("settings", views.settings, name="settings"),
    path("profile/<str:profile_owner_username>/", views.profile, name="profile"),
    path("delete_account", views.delete_account, name="delete_account"),
    path("delete_post", views.delete_post, name="delete_post"),
    path("book_post", views.book_post, name="book_post"),
    path("preview/", generate_preview.generate_preview, name="generate"),
    path("search", views.search, name="search"),
    path("follow", views.follow, name="follow"),
    path("join", views.join, name="join"),
    path("about/", views.about, name="about"),
    path("tags", views.tags_index, name="tags_index"),
    path("tags/wiki-data-search", views.tag_wiki_data_search, name="tag_wiki_data_search"),
    path("tags/search", views.tags_search, name="tags_search"),
    path("tags/all", views.all_tags, name="all_tags"),
    path("tags/<str:tag_name>", views.tag_posts, name="tag_posts"),
    path("spaces", views.spaces_index, name="spaces_index"),
    path("spaces/search", views.spaces_search, name="spaces_search"),
    path("spaces/create", views.create_space, name="create_space"),
    path("spaces/all", views.all_spaces, name="all_spaces"),
    path("spaces/<str:space_name>", views.space_posts, name="space_posts"),
    path("post/detail/<str:post_id>", views.post_detail, name="post_detail"),
    path("post/create", views.create_post, name="create_post"),
    path("post/update", views.update_post, name="update_post"),
    path("post/like/<str:post_id>", views.like_post, name="like_post"),
    path("post/dislike/<str:post_id>", views.dislike_post, name="like_post"),
    path("post/bookmark/<str:post_id>", views.bookmark_post, name="bookmark_post"),
    path("fetch-og-tags", views.fetch_og_tags, name="fetch_og_tags"),
    path("badges", views.badges, name="badges"),
]

SWE574/core/src/models/post_model_handler.py
"""Contains utility methods for Post model"""
from ...models import Post, Tag, Space, SemanticTag
from django.http import HttpResponseRedirect
from django.contrib import messages
from ..utils.generate_preview import generate_preview_


def create_post(request: object) -> None:
    """
    Implementation of creating a Post model and saving it to database
    @param request: HttpRequest object that contains metadata about request passed from frontend
    @return: None
    """
    # Get the user that requests to create a post
    owner = request.user
    # Get preview details
    preview = generate_preview_(url=request.POST.get('link'))
    # Creating new post
    if preview:
        new_post = Post.objects.create(owner=owner,
                                       link=request.POST.get("link"),
                                       caption=request.POST.get("caption"),
                                       title=preview.get('title'),
                                       description=preview.get('description'),
                                       preview_image=preview.get('image')
                                       )
    else:
        new_post = Post.objects.create(owner=owner,
                                       link=request.POST.get("link"),
                                       caption=request.POST.get("caption"),
                                       )

    tags = request.POST.getlist('tags[]')
    for tagId in tags:
        """ if tagId is not a number, it means that the tag is not in the database. So, we need to create a new tag """
        if not tagId.isdigit():
            tag = Tag.objects.create(name=tagId)
        else:
            tag = Tag.objects.get(id=tagId)

        new_post.tags.add(tag)

    semantic_tags = request.POST.getlist('semanticTagValues[]')
    semantic_tag_labels = request.POST.getlist('semanticTagLabels[]')
    for value in semantic_tags:
        wikidata_id = value.split("|")[0]
        label = value.split("|")[1]
        description = value.split("|")[2]
        custom_label = semantic_tag_labels[semantic_tags.index(value)]

        new_semantic_tag = SemanticTag.objects.create(wikidata_id=wikidata_id, label=label, description=description,
                                                      custom_label=custom_label, post=new_post)
        new_post.semantic_tags.add(new_semantic_tag)

    spaces = request.POST.getlist('spaces[]')
    if spaces:
        for space in spaces:
            space = Space.objects.get(name=space)
            new_post.spaces.add(space)
    new_post.save()
    # Print the tags


def update_post(request: object) -> None:
    """
    Implementation of updating an existing a Post model and saving the updated version to database
    @param request: HttpRequest object that contains metadata about request passed from frontend
    @return: None
    """
    # Get the existing post
    current_post = Post.objects.get(post_id=request.POST.get("post_id"))
    # Extract fields from request
    link = request.POST.get('link')
    caption = request.POST.get("caption")
    preview_image = request.POST.get("preview_image")
    # Modify existing post
    if link:
        current_post.link = link
    if caption:
        current_post.caption = caption
    preview = generate_preview_(url=link)
    if preview:
        current_post.title = preview.get('title')
        current_post.description = preview.get('description')
        if not preview_image:
            current_post.preview_image = preview.get('image')
        else:
            current_post.preview_image = preview_image
    # Reset the tags
    current_post.tags.clear()
    # Reassign the keys
    tags = request.POST.getlist('tags[]')
    for tagId in tags:
        """ if tagId is not a number, it means that the tag is not in the database. So, we need to create a new tag """
        if not tagId.isdigit():
            tag = Tag.objects.create(name=tagId)
        else:
            tag = Tag.objects.get(id=tagId)

        current_post.tags.add(tag)

    current_post.semantic_tags.all().delete()

    semantic_tags = request.POST.getlist('semanticTagValues[]')
    semantic_tag_labels = request.POST.getlist('semanticTagLabels[]')
    for value in semantic_tags:
        wikidata_id = value.split("|")[0]
        label = value.split("|")[1]
        description = value.split("|")[2]
        custom_label = semantic_tag_labels[semantic_tags.index(value)]

        new_semantic_tag = SemanticTag.objects.create(wikidata_id=wikidata_id, label=label, description=description,
                                                      custom_label=custom_label, post=current_post)

        current_post.semantic_tags.add(new_semantic_tag)

    space_names = request.POST.getlist('spaces[]')
    if space_names:
        current_post.spaces.clear()
        for space_name in space_names:
            space = Space.objects.get(name=space_name)
            current_post.spaces.add(space)
    current_post.save()


def __delete_post__(request: object) -> HttpResponseRedirect:
    """
    Implementation of deleting a Post model from database.
    @param request: HttpRequest object that contains metadata about request passed from frontend
    @return: Redirects the user to the current page
    """
    try:
        post_id = request.GET.get('post_id')
        # Delete the Post
        post = Post.objects.filter(post_id=post_id)
        post.delete()
        messages.success(request, "The Post is deleted")
    except Exception as e:
        print("Error is:", e)
    redirect_path = '/profile/' + request.user.username
    return HttpResponseRedirect(redirect_path)

SWE574/core/src/models/profile_model_handler.py
"""Contains utility methods for Profile model"""
from ...models import Profile
from django.contrib.auth.models import User
import random


def create_profile(request: object) -> None:
    """
    Implementation of creating a Profile model.
    @param request: HttpRequest object that contains metadata about request passed from frontend
    @return: None
    """
    username = request.POST.get("username")
    # Create profile object for the new user
    bg_img = f"background_images/bg-image-{random.randint(1, 5)}.jpg"  # Set background image dynamically
    user_model = User.objects.get(username=username)
    new_profile = Profile.objects.create(user=user_model, background_image=bg_img)
    new_profile.available_labels.append('default')
    new_profile.save()

SWE574/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class CommentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)

SWE574/core/src/controllers/annotation_controller.py
""" annotation controller """
import requests
from django.http import JsonResponse
import json
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
import uuid
import os
import environ

# read environment variables
current_directory = os.getcwd()
env = environ.Env()
environ.Env.read_env('/app/LinkMe/.env')


@csrf_exempt
def create_annotation(request):
    if request.method == 'POST':
        # Access the request body
        body = request.body.decode('utf-8')
        annotation = json.loads(body)
        """ if isset annotation['image_selection'] """
        if 'image_selection' in annotation:
            return convert_image_annotation_to_ldp_format(request, annotation)
        else:
            return convert_text_annotation_to_ldp_format(request, annotation)

        return JsonResponse({'status': 'fail'}, safe=False)


def convert_image_annotation_to_ldp_format(request, annotation):
    random_uuid = uuid.uuid4()

    annotation_ldp = {
        "@context": "http://www.w3.org/ns/anno.jsonld",
        "id": annotation['uri'] + "/annotations/" + str(random_uuid),
        "type": "Annotation",
        "motivation": "highlighting",
        "created": timezone.now().isoformat(),
        "target": {
            "source": annotation['image_selection']['src'],
            "selector": {
                "type": "FragmentSelector",
                "conformsTo": "http://www.w3.org/TR/media-frags/",
                "value": "xywh=percent:" + annotation['image_selection']['x'] + "," + annotation['image_selection'][
                    'y'] + "," + annotation['image_selection']['w'] + "," + annotation['image_selection']['h'],
            },
        },
        "body": {
            "type": "TextualBody",
            "value": annotation['text'],
            "format": "text/plain"
        },
        "creator": request.user.id,
    }

    """ send annotation_ldp to ldp server """
    ANNOTATION_URL = env('ANNOTATION_SERVICE_URL') + "/annotations/"
    requests.post(ANNOTATION_URL, json=annotation_ldp)
    return JsonResponse(annotation, safe=False)


def convert_text_annotation_to_ldp_format(request, annotation):
    random_uuid = uuid.uuid4()
    ranges = annotation['ranges'][0]
    referrer = request.META['HTTP_REFERER']
    annotation_ldp = {
        "@context": "http://www.w3.org/ns/anno.jsonld",
        "id": referrer + "/annotations/" + str(random_uuid),
        "type": "Annotation",
        "motivation": "highlighting",
        "created": timezone.now().isoformat(),
        "target": {
            "source": referrer,
            "selector": {
                "type": "RangeSelector",
                "startSelector": {
                    "type": "XPathSelector",
                    "value": ranges['start']
                },
                "endSelector": {
                    "type": "XPathSelector",
                    "value": ranges['end']
                },
                "startOffset": ranges['startOffset'],
                "endOffset": ranges['endOffset']
            }
        },
        "body": {
            "type": "TextualBody",
            "value": annotation['text'],
            "format": "text/plain"
        },
        "creator": request.user.id
    }

    """ send annotation_ldp to ldp server """
    ANNOTATION_URL = env('ANNOTATION_SERVICE_URL') + "/annotations/"
    requests.post(ANNOTATION_URL, json=annotation_ldp)
    return JsonResponse(annotation, safe=False)


def get_annotations(request):
    # read environment variables
    if request.method == 'GET':
        q = request.GET.get('uri')

        annotations = requests.get(env('ANNOTATION_SERVICE_URL') + "/annotations/search?query=" + q).json()
        json = {
            "total": len(annotations),
            "rows": []
        }
        for annotation in annotations:
            if annotation['target']['selector']['type'] == "FragmentSelector":
                selector = annotation['target']['selector']['value']
                x = selector.split('=percent:')[1].split(',')[0]
                y = selector.split('=percent:')[1].split(',')[1]
                w = selector.split('=percent:')[1].split(',')[2]
                h = selector.split('=percent:')[1].split(',')[3]
                json['rows'].append({
                    "image_selection": {
                        "src": annotation['target']['source'],
                        "uri": annotation['target']['source'],
                        "x": x,
                        "y": y,
                        "w": w,
                        "h": h,
                    },
                    "text": annotation['body']['value'],
                })
            else:
                json['rows'].append({
                    "quote": annotation['body']['value'],
                    "ranges": [
                        {
                            "start": annotation['target']['selector']['startSelector']['value'],
                            "startOffset": annotation['target']['selector']['startOffset'],
                            "end": annotation['target']['selector']['endSelector']['value'],
                            "endOffset": annotation['target']['selector']['endOffset']
                        }

                    ],
                    "uri": annotation['target']['source'],
                    "text": annotation['body']['value'],
                })

    return JsonResponse(json, safe=False)

SWE574/core/templates/about.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
{% endblock %}

{% block _navbar %}
    {% if user.is_authenticated %}
        <!-- Navbar for authenticated users -->
        <!-- Replace this section with your desired navbar for authenticated users -->
        <header class="navbar fixed-top navbar-expand-lg py-2" style="background-color: #006257;"
                aria-label="Fifth navbar example">
        <div class="container-fluid">
            <a class="navbar-brand mb-0 h1" href="#">
                <img src="{% static 'assets/images/logo/svg/logo-no-background.svg' %}" width="100"
                     class="d-inline-block align-top" alt="">
            </a>
            <button class="navbar-toggler ms-auto me-3" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse justify-content-md-center" id="navbarNav">
                <br>
                <form type="search" method="POST" id="search-form" action="{% url 'core:search' %}">
                    {% csrf_token %}
                    <input class="form-control me-0 input" type="search" placeholder="Search" aria-label="Search"
                           name="keyword">
                </form>
                <button type="submit" form="search-form" class="btn btn-primary button" id="search-button">
                    <i class="fas fa-search"></i>
                </button>
                <ul class="navbar-nav position-relative ms-0 me-auto">
                    <li class="nav-item">
                        <a href="/feed" class="nav-link px-3 text-white">Feed</a>
                    </li>
                    <!-- # TODO: Implement Discover -->
                    <li class="nav-item">
                        <a href="{% url 'core:tags_index' %}" class="nav-link px-3 text-white">Tags</a>
                    </li>
                    <!-- # TODO: Implement Spaces -->
                    <li class="nav-item">
                        <a href="{% url 'core:spaces_index' %}" class="nav-link px-3 text-white">Spaces</a>
                    </li>
                </ul>
            </div>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <!-- <img width="35" height="35" src="{{request_owner_user_profile.profile_image.url}}" class="header-avatar" alt="Dropdown"> -->
                    </a>
                    <div class="dropdown-menu" style="background-color: #006257;" aria-labelledby="dropdown03">
                        <a class="dropdown-item text-white"
                           href="{% url 'core:profile' profile_owner_username=request.user.username %}">{{ request.user.username }}</a>
                        <a class="dropdown-item text-white" href="/settings">Settings</a>
                        <a class="dropdown-item text-white" href="{% url 'core:about' %}">About</a>
                        <a class="dropdown-item text-white" href="{% url 'core:logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav position-relative ms-auto me-0">
                <li class="nav-item">
                    <a href="{% url 'core:profile' profile_owner_username=request.user.username %}"
                       class="nav-link px-3 text-white">
                        <img width="40" height="40" src="{{ request.user.profile.profile_image.url }}"
                             class="header-avatar"
                             alt="Dropdown">
                    </a>
                </li>
            </ul>
        </div>
    {% else %}
        <!-- Navbar for non-authenticated users -->
        <!-- Replace this section with your desired navbar for non-authenticated users -->
        <div class="navbar-collapse collapse " id="navbarNav">
            <br>
            <form type="search">
                <input class="form-control me-0" type="search" placeholder="Search" aria-label="Search">
            </form>
            <ul class="navbar-nav position-relative ms-0 me-auto">
                <li class="nav-item">
                    <a href="" class="nav-link px-3 text-white">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'core:about' %}" class="nav-link px-3 text-gray disabled">About</a>
                </li>
            </ul>
            <ul class="navbar-nav position-relative me-0">
                <li class="nav-item">
                    <a class="nav-link px-3 text-white" aria-current="page" href="/signup">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-3 text-white" aria-current="page" href="/signin">Sign In</a>
                </li>
            </ul>
        </div>
    {% endif %}
{% endblock %}

{% block content %}
    <html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>About Us</title>
        <style>
            body {
                background-image: url('../../static/assets/images/bg/stacked-peaks-haikei-1.svg');
                background-size: cover;
                background-repeat: no-repeat;
                background-attachment: fixed;
            }

            .container {
                margin-left: 0;
            }

            .row {
                margin-left: -100;
            }

            .collapsible {
                cursor: pointer;
            }

            .content {
                display: none;
                padding: 0 18px;
                overflow: hidden;
                transition: max-height 0.2s ease-out;
            }
        </style>
    </head>

    <body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="collapsible" onclick="toggleCollapsible('intro')">Introduction <i
                        class="fa fa-chevron-down"></i>
                </h1>
                <div class="content" id="intro">
                    <p>LinkMe is a social media platform where users can search, post, and save posts in their
                        accounts.</p>
                    <p>With LinkMe, you can explore the world and stay connected with others.</p>
                </div>

                <h1 class="collapsible" onclick="toggleCollapsible('faq')">FAQ <i class="fa fa-chevron-down"></i></h1>
                <div class="content" id="faq">
                    <p style="font-weight: bold">1) How to post new updates?</p>
                    <p>Sign in to your account and when you signed in, on the right corner you can see the "Post Link"
                        button.</p>
                    <p style="font-weight: bold">2) How can I like posts?</p>
                    <p>When you see a post, you can easily click the like button.</p>
                    <p style="font-weight: bold">3) Can I add tags?</p>
                    <p>Yes, you can easily add tags.</p>
                    <p style="font-weight: bold">4) Can I delete my posts?</p>
                    <p>Yes, you can easily delete your posts.</p>
                    <p style="font-weight: bold">5) Can I update my profile?</p>
                    <p>Yes, you can update your profile from the sidebar.</p>
                    <p style="font-weight: bold">6) Can I delete my profile?</p>
                    <p>Yes, you can delete your profile.</p>
                    <p style="font-weight: bold">7) Can I chat with other people?</p>
                    <p>Unfortunately, we are still working on this feature!</p>
                </div>

                <h1 class="collapsible" onclick="toggleCollapsible('arch')">Architecture <i
                        class="fa fa-chevron-down"></i>
                </h1>
                <div class="content" id="arch">
                    <p>You can see our Use Case Diagram below:</p>
                    <img src="{% static 'useCaseDiagram.png' %}" alt="Architecture Image"
                         style="max-width: 100%;">
                </div>
            </div>
        </div>
    </div>

    <script>
        function toggleCollapsible(id) {
            var content = document.getElementById(id);
            content.style.display = content.style.display === "none" ? "block" : "none";
        }
    </script>
    </body>
    </html>
{% endblock %}

SWE574/core/templates/debookmark_modal.html
<!-- Bookmark Modal -->
<div class="modal fade" id="debookmarkModal" tabindex="-1" aria-labelledby="debookmarkModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="debookmarkModalLabel">Bookmark Modal</h5>
            </div>
            <div class="modal-body">
                <label for="bookmark_name" class="col-form-label"><strong>Available
                    Bookmarks</strong></label>
                {% for label in request.user.profile.available_labels %}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="bookmark-checkbox"
                               value="{{ label }}" id="bookmark-{{ label }}">
                        <label class="form-check-label">
                            {{ label }}
                        </label>
                    </div>
                {% endfor %}
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" data-bs-dismiss="modal"
                        onclick="return bookmarkPost('update')">
                    Update
                </button>
                <button type="submit" class="btn btn-danger" data-bs-dismiss="modal"
                        onclick="return bookmarkPost('delete')">
                    De-Bookmark
                </button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

SWE574/core/templates/navbar.html
{% load static %}
<header class="navbar fixed-top navbar-expand-lg py-2" style="background-color: #006257;"
        aria-label="Fifth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand mb-0 h1" href="/feed">
            <img src="{% static 'assets/images/logo/svg/logo-no-background.svg' %}" width="100"
                 class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler ms-auto me-3" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse justify-content-md-center" id="navbarNav">
            <br>
            <form type="search" method="POST" id="search-form" action="{% url 'core:search' %}">
                {% csrf_token %}
                <input class="form-control me-0 input" type="search" placeholder="Search" aria-label="Search"
                       name="keyword">
            </form>
            <button type="submit" form="search-form" class="btn btn-primary button ms-2" id="search-button">
                <i class="fas fa-search"></i>
            </button>
            <ul class="navbar-nav position-relative ms-0 me-auto">
                <li class="nav-item">
                    <a href="/feed" class="nav-link px-3 text-white">Feed</a>
                </li>
                <!-- # TODO: Implement Discover -->
                <li class="nav-item">
                    <a href="{% url 'core:tags_index' %}" class="nav-link px-3 text-white">Tags</a>
                </li>
                <!-- # TODO: Implement Spaces -->
                <li class="nav-item">
                    <a href="{% url 'core:spaces_index' %}" class="nav-link px-3 text-white">Spaces</a>
                </li>
            </ul>
        </div>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <!-- <img width="35" height="35" src="{{request_owner_user_profile.profile_image.url}}" class="header-avatar" alt="Dropdown"> -->
                </a>
                <div class="dropdown-menu" style="background-color: #006257;" aria-labelledby="dropdown03">
                    <a class="dropdown-item text-white"
                       href="{% url 'core:profile' profile_owner_username=request.user.username %}">{{ request.user.username }}</a>
                    <a class="dropdown-item text-white" href="/settings">Settings</a>
                    <a class="dropdown-item text-white" href="{% url 'core:about' %}">About</a>
                    <a class="dropdown-item text-white" href="{% url 'core:logout' %}">Logout</a>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav position-relative ms-auto me-0">
            <li class="nav-item">
                <a href="{% url 'core:profile' profile_owner_username=request.user.username %}"
                   class="nav-link px-3 text-white">
                    <img width="40" height="40" src="{{ request.user.profile.profile_image.url }}"
                         class="header-avatar"
                         alt="Dropdown">
                </a>
            </li>
        </ul>
    </div>
</header>