SWE574/core/urls.py
from django.urls import path
from . import views
from .src.controllers import annotation_controller
from .src.utils import generate_preview

app_name = "core"

urlpatterns = [
    path("", views.feed, name="feed"),
    path("feed", views.feed, name="preview"),
    path("signup", views.signup, name="signup"),
    path("signin", views.signin, name="signin"),
    path("logout", views.logout, name="logout"),
    path("settings", views.settings, name="settings"),
    path("profile/<str:profile_owner_username>/", views.profile, name="profile"),
    path("about/", views.about, name="about"),
    path("delete_account", views.delete_account, name="delete_account"),
    path("delete_post", views.delete_post, name="delete_post"),
    path("preview/", generate_preview.generate_preview, name="generate"),
    path("search", views.search, name="search"),
    path("follow", views.follow, name="follow"),
    path("join", views.join, name="join"),
    path("tags", views.tags_index, name="tags_index"),
    path("tags/wiki-data-search", views.tag_wiki_data_search, name="tag_wiki_data_search"),
    path("tags/search", views.tags_search, name="tags_search"),
    path("tags/all", views.all_tags, name="all_tags"),
    path("tags/<str:tag_name>", views.tag_posts, name="tag_posts"),
    path("spaces", views.spaces_index, name="spaces_index"),
    path("spaces/search", views.spaces_search, name="spaces_search"),
    path("spaces/create", views.create_space, name="create_space"),
    path("spaces/all", views.all_spaces, name="all_spaces"),
    path("spaces/<str:space_name>", views.space_posts, name="space_posts"),
    path("post/detail/<str:post_id>", views.post_detail, name="post_detail"),
    path("post/create", views.create_post, name="create_post"),
    path("post/update", views.update_post, name="update_post"),
    path("post/like/<str:post_id>", views.like_post, name="like_post"),
    path("post/dislike/<str:post_id>", views.dislike_post, name="like_post"),
    path("post/bookmark_post", views.bookmark_post, name="bookmark_post"),
    path("fetch-og-tags", views.fetch_og_tags, name="fetch_og_tags"),
    path("annotations/create", annotation_controller.create_annotation, name="create_annotation"),
    path("annotations/search", annotation_controller.get_annotations, name="get_annotations"),
    path("badges", views.badges, name="badges"),
    path('add-comment/<uuid:post_id>/', views.add_comment, name='add_comment'),
    path('delete-comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path("following_list", views.following_list, name="following_list"),
    path("follower_list", views.follower_list, name="follower_list"),
]

core/urls.py
from django.urls import path
from . import views
from .src.utils import generate_preview

app_name = "core"

urlpatterns = [
    path("", views.feed, name="feed"),
    path("feed", views.feed, name="preview"),
    path("signup", views.signup, name="signup"),
    path("signin", views.signin, name="signin"),
    path("logout", views.logout, name="logout"),
    path("settings", views.settings, name="settings"),
    path("profile/<str:profile_owner_username>/", views.profile, name="profile"),
    path("delete_account", views.delete_account, name="delete_account"),
    path("delete_post", views.delete_post, name="delete_post"),
    path("book_post", views.book_post, name="book_post"),
    path("preview/", generate_preview.generate_preview, name="generate"),
    path("search", views.search, name="search"),
    path("follow", views.follow, name="follow"),
    path("join", views.join, name="join"),
    path("about/", views.about, name="about"),
    path("tags", views.tags_index, name="tags_index"),
    path("tags/wiki-data-search", views.tag_wiki_data_search, name="tag_wiki_data_search"),
    path("tags/search", views.tags_search, name="tags_search"),
    path("tags/all", views.all_tags, name="all_tags"),
    path("tags/<str:tag_name>", views.tag_posts, name="tag_posts"),
    path("spaces", views.spaces_index, name="spaces_index"),
    path("spaces/search", views.spaces_search, name="spaces_search"),
    path("spaces/create", views.create_space, name="create_space"),
    path("spaces/all", views.all_spaces, name="all_spaces"),
    path("spaces/<str:space_name>", views.space_posts, name="space_posts"),
    path("post/detail/<str:post_id>", views.post_detail, name="post_detail"),
    path("post/create", views.create_post, name="create_post"),
    path("post/update", views.update_post, name="update_post"),
    path("post/like/<str:post_id>", views.like_post, name="like_post"),
    path("post/dislike/<str:post_id>", views.dislike_post, name="like_post"),
    path("post/bookmark/<str:post_id>", views.bookmark_post, name="bookmark_post"),
    path("fetch-og-tags", views.fetch_og_tags, name="fetch_og_tags"),
    path("badges", views.badges, name="badges"),
]

SWE574/core/models.py
from uuid import uuid4
from django.contrib.auth.models import User
from django.db import models
from model_utils.models import TimeStampedModel
from django.core.validators import URLValidator
from django.contrib.postgres.fields import ArrayField


# override the default user model
class User(User):
    class Meta:
        proxy = True


class Profile(TimeStampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    bio = models.TextField(default="Write something here", max_length=100)
    profile_image = models.ImageField(upload_to="profile_images", default="profile_images/blank-profile-picture.png")
    background_image = models.ImageField(upload_to="background_images",
                                         default="background_images/bg-image-5.jpg")
    followers = models.ManyToManyField('self', related_name='following', symmetrical=False)
    available_labels = ArrayField(models.CharField(max_length=255), default=list, blank=True)

    def __str__(self):
        return self.user.username

    def all_labels(self):
        bookmarks = Bookmark.objects.filter(user=self.user)
        unique_labels = bookmarks.values_list('label_name', flat=True).distinct()
        return unique_labels

    def all_spaces(self):
        return Space.objects.all()

    # Overwrite delete method since OneToOne relationship does not delete User, Either we should use ForeignKey or
    # See: https://stackoverflow.com/questions/12754024/onetoonefield-and-deleting
    def delete(self, *args, **kwargs):
        self.user.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

    def sorted_posts_all(self):
        """Returns all posts of the profile in ascending order by edit date"""
        return self.user.posts.all().order_by("-modified")

    def sorted_bookmarked_posts_all(self):
        return self.user.posts_bookmarked.all().order_by("-modified")


class Post(TimeStampedModel):
    # Fields that are automatically filled
    post_id = models.UUIDField(primary_key=True, default=uuid4, unique=True)
    # likes with created
    likes = models.ManyToManyField(User, related_name='liked_posts', through='Like')
    dislikes = models.ManyToManyField(User, related_name='disliked_posts', through='Dislike')
    # bookmarks with created
    bookmarks = models.ManyToManyField(User, related_name='bookmarked_posts', through='Bookmark')
    # posts must belong to a user
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts', blank=False)
    # Fields that are filled by owner user
    link = models.URLField(blank=False, validators=[URLValidator])
    caption = models.TextField(blank=True)  # Caption can be empty
    # Preview attributes
    title = models.TextField(max_length=100, blank=True)
    description = models.TextField(max_length=500, blank=True)
    preview_image = models.TextField(max_length=200, blank=True)
    # Many-to-many field for tags
    tags = models.ManyToManyField('Tag', related_name='posts', default=None)
    spaces = models.ManyToManyField('Space', related_name='posts', default=None)
    # Many-to-many field for comments
    comments = models.ManyToManyField(User, related_name='commented_posts', through='Comment')

    def __str__(self):
        return self.owner.username

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()

    def total_bookmarks(self):
        return self.bookmarks.count()

    def tags_as_json_string(self):
        """ name: tag_name, id: tag_id """
        return [{"name": tag.name, "id": tag.id} for tag in self.tags.all()]

    def semantic_tags_as_json_string(self):
        """ name: tag_name, id: tag_id """
        return [{"id": tag.id, "wikidata_id": tag.wikidata_id, "label": tag.label,
                 "description": tag.description, "custom_label": tag.custom_label} for tag in self.semantic_tags.all()]

    def spaces_as_json_string(self):
        return [{"name": space.name, "id": space.id} for space in self.spaces.all()]

    def __setattr__(self, name, value):
        """Override __setattr_ method to freeze post_id, owner attributes"""
        if name == 'post_id':
            try:
                if value != self.post_id:
                    return
            except ValueError:
                pass
            except AttributeError:
                pass
            except Post.DoesNotExist:
                pass
        if name == 'owner':
            try:
                if value != self.owner:
                    return
            except Post.DoesNotExist:
                pass
        if name == 'link':
            if value == "":
                return

        super(self.__class__, self).__setattr__(name, value)

    def get_comments(self):
        return Comment.objects.filter(post=self)

    def self_label(self):
        """Get the bookmark label for a specific user. If the user has not bookmarked this post, return None."""
        bookmark = Bookmark.objects.filter(user=self.owner, post=self).first()
        return bookmark.label_name if bookmark else None


class Comment(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='commented_by_users')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts_commented')
    content = models.TextField()

    def __str__(self):
        return f"{self.user.username} - {self.content}"

    def self_label(self):
        """Get the bookmark label for a specific user. If the user has not bookmarked this post, return None."""
        bookmark = Bookmark.objects.filter(user=self.owner, post=self).first()
        return bookmark.label_name if bookmark else None


class Like(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='liked_by_users')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts_liked')

    def __str__(self):
        return self.user.username


class Bookmark(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='bookmarked_by_users')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts_bookmarked')
    label_name = models.CharField(max_length=25, blank=False, default="default")

    def __str__(self):
        return self.user.username


class Dislike(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='disliked_by_users')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts_disliked')

    def __str__(self):
        return self.user.username


class Tag(TimeStampedModel):
    name = models.CharField(max_length=25, unique=True)


class SemanticTag(TimeStampedModel):
    wikidata_id = models.CharField(max_length=25, unique=False)
    label = models.CharField(max_length=200, unique=False)
    description = models.CharField(max_length=500, unique=False)
    custom_label = models.CharField(max_length=200, unique=False, blank=True)
    """ belongs to one post, post has many semantic tags """
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='semantic_tags', unique=False,
                             blank=False, default=1)


class Space(TimeStampedModel):
    name = models.CharField(max_length=25, unique=True)
    avatar = models.ImageField(upload_to="space_images", default="space_images/default_space.jpg")
    description = models.CharField(max_length=100, blank=False, default="This is a Space!")
    subscribers = models.ManyToManyField(User, related_name='subscribed_users', through='Subscriber')


class Subscriber(TimeStampedModel):
    space = models.ForeignKey(Space, on_delete=models.CASCADE, related_name='subscribed_by_users')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='spaces_subscribed')

SWE574/core/src/models/profile_model_handler.py
"""Contains utility methods for Profile model"""
from ...models import Profile
from django.contrib.auth.models import User
import random


def create_profile(request: object) -> None:
    """
    Implementation of creating a Profile model.
    @param request: HttpRequest object that contains metadata about request passed from frontend
    @return: None
    """
    username = request.POST.get("username")
    # Create profile object for the new user
    bg_img = f"background_images/bg-image-{random.randint(1, 5)}.jpg"  # Set background image dynamically
    user_model = User.objects.get(username=username)
    new_profile = Profile.objects.create(user=user_model, background_image=bg_img)
    new_profile.available_labels.append('default')
    new_profile.save()

core/src/models/profile_model_handler.py
"""Contains utility methods for Profile model"""
from ...models import Profile
from django.contrib.auth.models import User


def create_profile(request: object) -> None:
    """
    Implementation of creating a Profile model.
    @param request: HttpRequest object that contains metadata about request passed from frontend
    @return: None
    """
    username = request.POST.get("username")
    # Create profile object for the new user
    user_model = User.objects.get(username=username)
    new_profile = Profile.objects.create(user=user_model)
    new_profile.save()
    pass

core/src/models/space_model_handler.py
from ...models import Space


def create_space(request: object):
    # TODO: Implement created/already exist Message, create a rule for tag names maybe?
    try:
        space_name = request.POST.get("space_name")
        space = Space.objects.create(name=space_name)
        space.save()
        # Message success here
    except Exception as e:
        print(f"{e=}")
        # Message failure here
        pass


def validate_space(request: object):
    # Validate does not exist
    space_name = request.POST.get("space_name")
    if Space.objects.filter(name=space_name).exists():
        print("Space already exist")
        return False
    else:
        print("Space name is valid")
        return True

core/src/models/tag_model_handler.py
from ...models import Tag, Post


def create_tag(request: object) -> None:
    # TODO: Implement created/already exist Message, create a rule for tag names maybe?
    try:
        tag_name = request.POST.get("tag_name")
        tag = Tag.objects.create(name=tag_name)
        tag.save()
        # Message success here
    except Exception as e:
        # Message failure here
        print(f"{e=}")
        pass


def reset_tags(post: Post):
    post.tags.clear()
    post.save()


def validate_tag(request: object):
    # Validate does not exist
    tag_name = request.POST.get("tag_name")
    if Tag.objects.filter(name=tag_name).exists():
        print("Tag already exist")
        return False
    else:
        print("Tag name is valid")
        return True

SWE574/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class CommentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)

core/templates/post_create_modal.html
<div class="modal fade" id="postModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create New Post</h5>
            </div>
            <div class="modal-body">
                <form action="{% url 'core:create_post' %}" method="POST" id="post_create_form">
                    {% csrf_token %}
                    <input name="form_name" type="hidden" id="form-name" value="post-create-form">
                    <!-- img preview -->
                    <img name="" id="preview_image" class="img-thumbnail" src="" alt="Image Preview"
                         style="width: 100%; height: 100%; display: none;">
                    <input name="preview_image" type="hidden" id="image">
                    <div class="form-group text-secondary">
                        <label for="link" class="col-form-label"><strong>URL</strong></label>
                        <input name="link" type="text" class="form-control" id="link" placeholder="Enter the link">
                        <hr>
                        <label for="caption" class="col-form-label"><strong>Caption</strong></label>
                        <textarea name="caption" class="form-control" id="caption"
                                  placeholder="Enter the caption"></textarea>
                        <hr>
                        <div class="d-grid gap-2" id="tagPanel">
                            {# Implementation of Tags #}
                            <input name="selectedTags" type="hidden" id="selectedTags">
                            <label for="tags" class="col-form-label"><strong>Tags</strong></label>
                            <select id="postCreateModalTags" name="tags[]" multiple="multiple">
                            </select>

                            {# Implementation of Semantic Tags #}
                            <label for="semanticTags" class="col-form-label"><strong>Semantic Tags</strong></label>
                            <select id="semanticTags" name="semanticTags[]" multiple="multiple">
                            </select>

                            <div id="semanticTagLabels">

                            </div>

                            {# Implementation of Spaces #}
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                Select Spaces
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                {% for space in request.user.profile.all_spaces %}
                                    <li>
                                        <div class="form-check">
                                            <input class="form-check-input position-static" type="checkbox"
                                                   style="margin-left: -1rem; float: none;"
                                                   id="space{{ forloop.counter }}" name="spaces[]"
                                                   value="{{ space.name }}">
                                            <label class="form-check-label ml-2"
                                                   for="space{{ forloop.counter }}">{{ space.name }}</label>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="close" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" form="post_create_form" class="btn btn-primary" onclick="return checkform();">
                    Create Post
                </button>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
<script>
    // post_create_form validation
    document.querySelector('#post_create_form').addEventListener('submit', function (e) {
        var link = document.querySelector('#postModal #link').value;
        var caption = document.querySelector('#postModal #caption').value;
        var tags = document.querySelector('#postModal #selectedTags').value;
        var spaces = document.querySelector('#postModal #spaces').value;

        if (link == "" && caption == "" && tags == "" && spaces == "") {
            alert("Please enter a valid URL, caption, tags or spaces");
            e.preventDefault();
        }

        if (!validateURL(link)) {
            alert("Please enter a valid URL");
            e.preventDefault();
        }
    });

    $('#postCreateModalTags').select2({
        dropdownParent: $('#postModal #tagPanel'),
        ajax: {
            url: '/tags/all',
            processResults: function (data) {
                return {
                    results: data.tags.map(function (tag) {
                        return {
                            id: tag.id,
                            text: tag.name
                        }
                    })
                };
            }
        },
        tags: true

    });

    $('#postModal #semanticTags').select2({
        dropdownParent: $('#postModal #tagPanel'),
        ajax: {
            url: "{% url 'core:tag_wiki_data_search' %}",
            data: function (params) {
                var query = {
                    search: params.term,
                    type: 'public'
                }

                // Query parameters will be ?search=[term]&type=public
                return query;
            },
            processResults: function (data) {
                return {
                    results: data.map(function (tag) {
                        return {
                            id: tag.id,
                            text: tag.name + " (" + tag.description + ")"
                        }
                    })
                };
            }
        }
    });

    $('#postModal #semanticTags').on('select2:select', function (e) {
        // create new input field for semantic tags in #semanticTagLabels
        var tag = e.params.data;
        var tagId = tag.id;
        var tagName = tag.text;
        var tagDescription = tag.text.split(" (")[1].split(")")[0];

        var newTag = document.createElement("div");
        newTag.setAttribute("class", "badge bg-secondary");
        newTag.setAttribute("id", "semanticTag_" + tagId);
        newTag.setAttribute("style", "margin: 5px;");
        newTag.innerHTML = tagName + "<i class='bi bi-x' onclick='removeSemanticTag(" + tagId + ")'></i>";

        document.querySelector("#semanticTagLabels").appendChild(newTag);
        // create text input under
        var newInput = document.createElement("input");
        newInput.setAttribute("name", "semanticTagLabels[]");
        newInput.setAttribute("class", "form-control");
        newInput.setAttribute("value", "");
        document.querySelector("#semanticTagLabels").appendChild(newInput);
        // create hidden input for to keep semantic tag values
        var newInput = document.createElement("input");
        newInput.setAttribute("name", "semanticTagValues[]");
        newInput.setAttribute("type", "hidden");
        newInput.setAttribute("value", tagId + "|" + tagName + "|" + tagDescription);
        document.querySelector("#semanticTagLabels").appendChild(newInput);
    });

    // validate the given text if it is a valid URL
    function validateURL(textval) {
        {#var urlregex = new RegExp(#}
        {#    "^(http:\/\/www.|https:\/\/www.|ftp:\/\/www.|www.){1}([0-9A-Za-z]+\.)");#}
        {#return urlregex.test(textval);#}
        return true;
    }

    // on paste on url input, validate the url and set the url to the input
    document.querySelector('#postModal #link').addEventListener('paste', function (e) {
        if (e.clipboardData) {
            var text = e.clipboardData.getData('text/plain');
            if (!validateURL(text)) {
                alert("Please enter a valid URL");
                return;
            } else {
                fetch("{% url 'core:fetch_og_tags' %}", {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify({
                        url: text
                    })
                }).then(response => response.json())
                    .then(data => {
                        var description = data.description;
                        var img = data.img;

                        if (description != null) {
                            document.querySelector('#postModal #caption').value = description;
                        }

                        if (img != null) {
                            document.querySelector('#postModal #preview_image').src = img;
                            document.querySelector('#postModal #preview_image').style.display = "block";
                            document.querySelector('#postModal [name="preview_image"]').value = img;
                        }
                    });
            }
        }
    });
</script>

core/templates/post_detail.html
{% extends "base_inside.html" %}

{% block content %}
<ul class="timeline">
    {% include "post_container.html" with post=post %}
</ul>
{% endblock %}

core/templates/test.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Preview</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</head>
<style>
    .not-visible {
        display: none;
    }
</style>

<body>
    <div class="container">
        <form action="" method="POST" id="url_preview_form">
            <div class="form-group">
                <input type="hidden" class="form-control" id="id_link" name="link" aria-describedby="emailHelp"
                    placeholder="Enter Url" value="https://www.youtube.com/watch?v=xSUm6iMtREA&t=11120s">
            </div>
        </form>
{#        <button type="submit" form="url_preview_form" class="btn btn-primary">#}
        <div class="spinner-border text-success not-visible" id="loader" role="status">
            <span class="sr-only">Loading...</span>
        </div>
        <div class="card mt-4 not-visible" style="width: 18rem;" id="card_div">
            <img id="preview_image" class="card-img-top" src="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded" alt="Card">
            <div class="card-body">
                <h5 class="card-title" id="title"></h5>
                <p class="card-text" id="desc"></p>
                <a id="link_btn" href="#" class="btn btn-primary">Go To Website</a>
            </div>
        </div>
    </div>
</body>
<script>
    title = document.getElementById('title');
    desc = document.getElementById('desc');
    image = document.getElementById('preview_image');
    link_btn = document.getElementById('link_btn');
    card = document.getElementById('card_div');
    loader = document.getElementById('loader');


    $("#id_link").ready(function () {
        let link = $('#id_link').val();
        console.log(link);
        $.ajax({
            url: '{% url 'core:generate' %}',
            data: {
                'link': link
            },
            dataType: 'json',
            beforeSend: function () {
                loader.classList.remove('not-visible');
                card.classList.add('not-visible');
            },
            success: function (response) {
                card.classList.remove('not-visible');
                title.innerHTML = response.title
                desc.innerHTML = response.description
                image.src = response.image
                link_btn.href = link
                loader.classList.add('not-visible');
            },
            error: function (error) {
                console.log(error);
            },
        });
    });
</script>

</html>